### PR TITLE
WIP: Adhere sum-type to static-sum-type specification

### LINKED ISSUE #6: Single static case for all unions  and pass the entire record instead of a spread of values.
I've found the current case style which spreads args creates brittle code.
Changing types leads to changing a lot of caller code to receive the values in a particular order.

And in the case of record style (which we will move to exclusively #4 ), we are relying on ordered keys which  is unspecified in JS.

I think instead there should be a single `case` function that works on any sum-type instance.

union-type tags instances for quick identification.  I'm a little torn if we should continue using this instead of simply verifying something has the correct shape (like sanctuary-def does).

Perhaps we could support both.  I'd really like to pass a pojo to a case function and it fires on the correct branch, but I wouldn't to sacrifice the performance that union-types strategy proved out.

### LINKED ISSUE #11: Generate type constructors automatically.
Generate Binary/Unary/NAry(?) type constructors automatically for each case of the union.

### LINKED ISSUE #23: Implement strict case along side existing case.
I think a great way to dog food the new API would be to include it alongside the existing one and then phase out the old one.

There's a few issues I currently have with `case` that I think could all be solved in one release.

- case provides a spread of args which leads to brittle code and can break `S.K( Nothing )` if the case has no values #6 
- the placeholder leads to code that can easily become unsafe when refactoring models #13 
- A static case that receives the type as the first arg, instead of a case method on each type #6 (we can implement this and then phase out the existing cases if the API works out
- An enforced name #14
- I think we should also specify the type signature of the case function so we can type check return types (currently its always Any).

The API would look something like this:

```js
const display_name = 
  Sum.case( 
    'JAForbes/get'
    ,{} //constraints
    ,[User, String] // signature
    ,{ Loaded: prop('user_name')
     , Id: K('loading...')
     , Empty: K('Create an account')
     }
)

display_name( User.Empty() ) //=> 'Create an Account'
display_name( User.Id(id) ) //=> 'loading...'
```

We'd get type errors if the case function returned the wrong type, we could form constraints with type variables in sum-type definitions.

### PR DESCRIPTION
**Pull request by JAForbes**
> Note: This is a very early merge request, all tests are failing, all the docs are still wrong. 

For the past 6 months I've been iterating on all the problems I have with the current API in a separate project: https://gitlab.com/JAForbes/static-sum-type

I've been using SST in production code in a few different places and I'm very happy with the interface.  This branch will be a major breaking change and close almost all open issues.  It will probably take me a few weeks to get this out the door as I don't have a lot of time but I've written an early rough draft of the API.

Changes

- Support SST
  - Compatible with all SST helper functions ( fold, map, bimap etc )
  - Each case contains a single value, not a list / record of values ( Thanks @kurtmilliam )
  - Instances are serializable, great for tests, localStorage, typed network data etc
  - Case names must at least start with one capital letter

- No more placeholder support ( Fixes #25 #13 )
- No more explicit support for prototypes/methods/instanceof ( Fixes #20 )
- All types are named ( Fixes #20 )
- Generate type constructors for every case ( Fixes #11 )
- Remove variadic spread in case functions ( Fixes #6, Fixes #24 )
- Only use sanctuary-def types, no more built ins or predicates ( Fixes #23 )
- Provide helper constructors for Predicated and Record unions ( Fixes #23 )
- Use sentinel values for recursive and unit types (instead of relying on `undefined` )
- No more instance case, just static
- Half as much code
- Only one type of constructor that accepts the value, instead of the variadic constructor and Of variant.
- No more generators to extract values, just grab them from the .value property
- No more _keys value to isolate metadata from user data ( with potential name collisions ), it's just there on it's own `value` namespace.
- Other stuff

I'll update this description as I go along.  I'm planning to release this as `v1.0.0` because I am using this in prod in a few apps so hiding behind semver minor is no longer accurate.  It's also such a dramatic change that I don't want people accidentally updating and breaking their apps.

I need these changes to make some problems I have at work go away, so despite having no time this is high priority for me.

### CODE REVIEW

**Comment by JAForbes** [comment]
Thinking I'm going to drop the sentinels for this release.  Recursive types are simpler to define with this new spec but I never use them and so I'm not sold on what the API should be.  Also I've personally found the `Maybe.Nothing` not being a function causes a lot of friction for me, I end up using `K(Nothing)` everywhere.  So I'm not sold on unit types either, I think I'd rather a nullary function.  But that's probably worth handling in another release too.

**Comment by JAForbes** [comment]
Same goes for predicates, I'll leave that to user land for now.

**Comment by JAForbes** [comment]
I've re-added a recursive definition, 

```js
const List = Recursive( List=> ({
  Nil: Unit
  , Cons: Pair( a, List ) 
}))
```

Unlike union-type, where it uses undefined as a pseudo sentinel value to refer to itself (something I'd prefer to throw an error), we make the type definition able to refer to itself by making it lazy via `=>`

I'm going to dogfood this for a while but I like it I think.  Also note the use of `Unit`, which in union type would have been `Nil: []`.  This is a consequence of how sum-type henceforth can only have 1 value (which solves so many problems).

**Comment by davidchambers** [comment]
These are exciting changes, @JAForbes!

**Comment by JAForbes** [comment]
Thank you @davidchambers 🎉

**Comment by JAForbes** [comment]
I've just published an alpha release under the `next` tag.  I'm going to try using it for some actual "real world" work and see how it fares.  I've been using sum-type as a static only api anyway, so it shouldn't a painful migration.  T.Named becomes T.Record essentially.

**Comment by JAForbes** [comment]
Using this for work I've found two things that are related and annoying.  One is: empty record types in the old version used to signify 0 values, so you could initialize a type with no args.  Now the constructor will do nothing if you pass in no args and didn't specifically specify `T.Unit` because it's expecting an empty object `{}` as a parameter.

I thought removing variadic constructors would solve the curried constructors problem #4 - but there's still this edge case.  So I'm going to uncurry the T.Record constructor.  Unfortunately this means I lose sanctuary-def's nice `function.toString` signature printing.  But I can live with that, and maybe in future I can add a patch release that recovers that toString without having this edge case.

Ideally it'd be great to get sanctuary type checking without opting in to currying.  But that might be a big ask.

**Comment by JAForbes** [comment]
The other annoying thing is T.Unit only works on T.Value/T.Recursive not on T.Record.  So I'll fix that too.

**Comment by JAForbes** [comment]
Here's a [demo](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIAKpIC8kgMoBXLNICeABxgAdNHvFSAqnBgAneTPwAlGHTMATABQByE+ZcVJwPZMkBxZXhiRCsjNAhiX0kKWwBzCAlzGAdQ4EllUzMAfUzzTBxQ6XwAEnxFYjMINDjJVj1WAEo9FrRDSQAZWgwHFMtigDUMKCDXLp6Uz29ogE1Q9zNoigA5IvxwyIbm-Tb6CUlMADdLaPHeh3xqDFMnHzQ-PznJBcvrmElb6IeAoIlQp0a8gAfJIXIoIHF7kZNC4vg9YjAEkkzCl-uk8jkMQV3k1gaCABIQSTEQjJUEAagxuSy2LhuLhK3+gLkIJcZ2qtXwXNh9zq2wMeyk5jMtDM0hgAA8pAowHi7n5Kuppry-GAAXCUcRlGZ7i5lrRJABRMwisw8vysSRXYjUQgfGCA+UPTXa+4wfA4OBwDBxXS8+poAN6MDKNrECD0SQAQU0mgBTvaKKRjBRDhOKoeL3iiRTKVuGSy1PyXFCLgAUlGAGKigBG8BcfOi0XacV+0skcL8L0CwXV92iLp13g7GcOEBgAHd453JIP7sgZ34sK5NCipi4jk5Ot1zvgZlukznkmnAY0XNtvt8KJvtxMLvvZ4ij6nJKfFzFly5CGaL5e-O+KE-VcYHXG8zhSPct1bYJX1fc8ALAncIIfaD9jfDMr0-b94Iwh4AKAtcvA3DBDi3cCLmWAE4N-P9rxIsikIoqiaMvQDXGwljvnwldCNBcj8EoyRUKkM9OPhAiQK8YVRXFKUtyollb13QThNgxoxL8Nivx-d9uJcYD134-dRL0gypJNGTJWIeTmRBIzmI0j92J03D-1cpz9N4tlGNeUwcL-TSJKmfirlMV89I43T3K0sy+J80KYHzJp-ICmLeOksUrJsvEQreJLT3C6KsJcgKR1KtLJNBI4UtooKvCOQryuKmrL1MrzN0PZEUhMoqeMqjLZOsj5bIOejH2TY81Ma1LmrEgBdOlogDIM0CwD1aFDayHFoahVBEfAa1oBx1C8GNNEaNgOBAbE8EuL1KBoehGGYHg2DmqgoGqABrBAUE4HA8DgVRiC0d0sGqfB+Ae7VyB4EhiE0OBEAAemR0NNC+uJLloLBkaBrAAFoQe0AABABGfAAAYqYJsxqAANjx4HQY9CGoaoYnuBAKH2H+rnwZJKpyCoGG8HhxGUbRtAMaxuhcYF79oHJ-AKYAVmRhWhchgQQE5vAebm1ggA) of this PR to test out the bundle.

**Comment by JAForbes** [comment]
Closing as I've been dogfooding v1 of sum-type over here https://gitlab.com/harth/stags and I'll bring those changes to this repo near term wholesale.

**Pull request closed without merging**
